name: Messaging
version: 1.2
main: com.stickms.messaging.Messaging
api-version: 1.13
authors: [ Jaconp ]
description: Allows players to privately message one another.
website: stickms.com
permissions:
  messaging.broadcast:
    description: Permission to use the broadcast command.
    default: op
